#!/bin/bash

if [ "$(git config hooks.ticketnumbercheck)" == "on" ]
then
    if head -n 1 "$1" | grep -Pvq "^#[0-9]+"
    then
        echo >&2 "ERROR: Ticket number is missing in commit message"
        exit 1
    fi
fi
