#!/bin/bash

# Check PHP file $1 syntax and exit with exit code 1 if there are any errors
test_php_file_syntax() {
    if [[ "$1" =~ .(php|inc)$ ]] && ! php -l "$1" > /dev/null;
    then
        echo
        echo -e "\e[31mPHP syntax checker failed\e[0m"
        echo
        echo -e "\tFile: \e[34m$1\e[0m"
        echo -e "\tReason:"
        echo
        php -l "$1" | sed "s/^/\t/"
        echo
        exit 1
    fi
}

# Check file $1 for words $2
test_words_existance() {
    if git diff --cached -U0 "$1" | grep -P '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/|-)' | grep -q "$2"
    then
        echo
        echo -e "\e[31mWords checker failed\e[0m"
        echo
        echo -e "\tFile: \e[34m$1\e[0m"
        echo -e "\tReason: has word \e[96m$2\e[0m in newly written code."
        git diff --cached -U0 "$1" | grep -P '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/|-)' | grep "$2" | sed "s/^/\t/" | cut -c 1-100
        echo
    fi
}

while read st file
do
    # skip deleted files
    if [ "$st" == 'D' ]
    then
        continue
    fi

    # Generic
    test_words_existance "$file" TODO
    test_words_existance "$file" FIXME
    test_words_existance "$file" XXX

    # PHP
    test_php_file_syntax "$file"
    test_words_existance "$file" var_dump
    test_words_existance "$file" print_r
    test_words_existance "$file" error_reporting
    test_words_existance "$file" debug_backtrace
    test_words_existance "$file" exit
    test_words_existance "$file" die

    # Mysql
    test_words_existance "$file" TRUNCATE
    test_words_existance "$file" DELETE

    # JavaScript
    test_words_existance "$file" console.log
    test_words_existance "$file" debugger

    # Python
    test_words_existance "$file" set_trace
    test_words_existance "$file" print
    test_words_existance "$file" pprint
    test_words_existance "$file" __dict__

    # Ruby
    test_words_existance "$file" abort
    test_words_existance "$file" debug
    test_words_existance "$file" inspect

done < <(git diff --cached --name-status)

# NOTE: Why we are not using `exit 1-255` on error? Well, in practice
# you would see that it's way too buggy to trust. Way too many times
# you are forced to use `git commit -n` to run commit without hooks,
# so errors are just printed out for the user.
