#!/bin/bash

# clean git default stuff
echo > "$1"

# if it's merge commit - write default message
if [ "$2" == "merge" ]
then
    echo "Code merge" > "$1"
fi

# if it contains some number in branch name - use it as ticket ID
TICKET=$(git symbolic-ref HEAD | sed 's/[^0-9]*//')
if [ -n "$TICKET" ]
then
    echo "#$TICKET " > "$1"
fi
