#!/bin/bash

# if it contains some number in branch name - use it as ticket ID
TICKET=$(git symbolic-ref HEAD | sed 's/[^0-9]*//')
if [ -n "$TICKET" ]
then
    mv "$1" "$1.bak"
    echo "#$TICKET " > "$1"
    cat "$1.bak" >> "$1"
    rm -f "$1.bak"
fi
