#!/bin/bash

if [ -z "$2" ]
then
    echo > "$1"

    # Ticket number as first commit entry
    if [ -f /tmp/.git-rejected-commit-msg ]
    then
        cat /tmp/.git-rejected-commit-msg | grep -v '^$' | grep -v '^*' > "$1"
        echo -e "\n" >> "$1"
    else
        TICKET=$(git symbolic-ref HEAD | sed 's/[^0-9]*//')
        if [ -n "$TICKET" ]
        then
            echo "#$TICKET " > "$1"
            echo -e "\n" >> "$1"
        else
            TICKET=$(git last --author="$(git config user.name)" --oneline | sed 's/.*\#\([0-9]*\).*/\1/')
            if [ -n "$TICKET" ] && [ "$(git last --author=$(git config user.name | sed 's/^\(.*\) .*$/\1/') --oneline)" != "$TICKET" ]
            then
                echo "#$TICKET " > "$1"
                echo -e "\n" >> "$1"
                echo "* Previous commits by me:" >> "$1"
                git log --author="$(git config user.name)" --oneline -n 3 | sed 's/^/*  /' >> "$1"
                echo -e "\n" >> "$1"
            else
                echo -e "\n" >> "$1"
            fi
        fi
    fi

    if [ "$(git config hooks.ticketnumbercheck)" == "on" ]
    then
        python -c "print '*' * 80" >> "$1"
        echo -e "* Commit without ticket number will be rejected!" >> "$1"
        python -c "print '*' * 80" >> "$1"
        echo -e "\n" >> "$1"
    fi

    python -c "print '*' * 80" >> "$1"
    echo "* You are on $(git branch | grep '^\*' | awk '{print $2}') branch." >> "$1"
    python -c "print '*' * 80" >> "$1"
    echo -e "\n" >> "$1"

    python -c "print '*' * 80" >> "$1"
    echo -e "* Changed files:" >> "$1"
    git status --porcelain | sed 's/^/*    /'  >> "$1"
    python -c "print '*' * 80" >> "$1"
    echo -e "\n" >> "$1"
fi
